alias: News Chip - Haberler 3
description: ''
trigger:
  - platform: state
    entity_id:
      - timer.news_timer_5m
    to: idle
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
        - input_boolean.news_chip_galatasaray
        - input_boolean.news_chip_fenerbahce
        - input_boolean.news_chip_besiktas
        - input_boolean.news_chip_haber
        - input_boolean.news_chip_trabzonspor
mode: single
