alias: News Chip - Haberler 6
description: ''
trigger:
  - platform: state
    entity_id:
      - input_boolean.news_chip_besiktas
      - input_boolean.news_chip_fenerbahce
      - input_boolean.news_chip_galatasaray
      - input_boolean.news_chip_trabzonspor
      - input_boolean.news_chip_haber
    to: 'on'
    from: 'off'
condition: []
action:
  - service: timer.start
    data: {}
    target:
      entity_id: timer.news_timer_5m
mode: single
