alias: Football Page - Trabzonspor
description: ''
trigger:
  - platform: state
    entity_id:
      - input_boolean.news_chip_besiktas
      - input_boolean.news_chip_fenerbahce
      - input_boolean.news_chip_galatasaray
      - input_boolean.news_chip_trabzonspor
      - input_boolean.news_chip_haber
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.trabzonspor
    state: 'on'
action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.news_chip_trabzonspor
mode: single
