alias: Football Page - News Chip Auto on - off
description: ''
trigger:
  - platform: template
    value_template: '{{ is_state(''input_boolean.news_chip_besiktas'', ''on'') }}'
    id: besiktas
  - platform: template
    value_template: '{{ is_state(''input_boolean.news_chip_fenerbahce'', ''on'') }}'
    id: fenerbahce
  - platform: template
    value_template: '{{ is_state(''input_boolean.news_chip_trabzonspor'', ''on'') }}'
    id: trabzonspor
  - platform: template
    value_template: '{{ is_state(''input_boolean.news_chip_galatasaray'', ''on'') }}'
    id: galatasaray
  - platform: template
    value_template: '{{ is_state(''input_boolean.news_chip_haber'', ''on'') }}'
    id: haber
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: besiktas
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.news_chip_trabzonspor
                - input_boolean.news_chip_galatasaray
                - input_boolean.news_chip_fenerbahce
                - input_boolean.news_chip_haber
      - conditions:
          - condition: trigger
            id: fenerbahce
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.news_chip_trabzonspor
                - input_boolean.news_chip_galatasaray
                - input_boolean.news_chip_besiktas
                - input_boolean.news_chip_haber
      - conditions:
          - condition: trigger
            id: trabzonspor
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.news_chip_fenerbahce
                - input_boolean.news_chip_galatasaray
                - input_boolean.news_chip_besiktas
                - input_boolean.news_chip_haber
      - conditions:
          - condition: trigger
            id: galatasaray
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.news_chip_fenerbahce
                - input_boolean.news_chip_trabzonspor
                - input_boolean.news_chip_besiktas
                - input_boolean.news_chip_haber
      - conditions:
          - condition: trigger
            id: haber
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.news_chip_fenerbahce
                - input_boolean.news_chip_trabzonspor
                - input_boolean.news_chip_besiktas
                - input_boolean.news_chip_galatasaray
    default: []
mode: single
