alias: News Chip - Haberler 5
description: ''
trigger:
  - platform: template
    value_template: >-
      {{ is_state('input_boolean.news_chip_trabzonspor', 'off') and
      is_state('input_boolean.news_chip_besiktas', 'off') and
      is_state('input_boolean.news_chip_fenerbahce', 'off') and
      is_state('input_boolean.news_chip_haber', 'off') and
      is_state('input_boolean.news_chip_galatasaray', 'off') }}
    id: start-news
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.news_chip_all
mode: single
